service: Booki-system-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  handler:
    handler: src/handlers.handler
    events:
      - http:
          path: /
          method: get

      - http:
          path: /connectDatabase
          method: get
      
      - http:
          path: /api/register
          method: post

      - http:
          path: /api/login
          method: post

plugins:
  - serverless-plugin-typescript